# Generated by Django 5.2.4 on 2025-07-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tourist', 'Tourist'), ('organizer', 'Organizer'), ('admin', 'Admin')], default='tourist', max_length=20),
        ),
    ]
