# Generated by Django 5.2.4 on 2025-07-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('regular', 'Regular'), ('google', 'Google'), ('facebook', 'Facebook')], default='regular', max_length=10),
        ),
    ]
