# Generated by Django 5.2.4 on 2025-07-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tourist', 'Tourist'), ('organizer', 'Organizer'), ('guide', 'Guide'), ('admin', 'Admin')], default='tourist', max_length=20),
        ),
    ]
