# Generated by Django 5.2.4 on 2025-07-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Nature', 'Nature'), ('Cultural', 'Cultural'), ('Beach', 'Beach'), ('Historical', 'Historical')], default='Adventure', max_length=50),
        ),
    ]
