# Generated by Django 5.2.4 on 2025-07-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_category'),
    ]

    operations = [
    ]
