# Generated by Django 5.2.4 on 2025-07-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='cover_image',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Nature', 'Nature'), ('Cultural', 'Cultural'), ('Beach', 'Beach'), ('Historical', 'Historical')], default='', max_length=200),
        ),
    ]
