# Generated by Django 5.2.4 on 2025-08-03 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_guide_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='guide',
        ),
        migrations.AddField(
            model_name='tour',
            name='guides',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.guide'),
        ),
        migrations.AddField(
            model_name='tour',
            name='participants',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'tourist'}, related_name='joined_tours', through='tours.TourParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(default='Adventure', max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cover_image',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tour',
            name='organizer',
            field=models.ForeignKey(limit_choices_to={'role': 'organizer'}, on_delete=django.db.models.deletion.CASCADE, related_name='organized_tours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourparticipant',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_participants', to='tours.tour'),
        ),
        migrations.AlterField(
            model_name='tourparticipant',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'tourist'}, on_delete=django.db.models.deletion.CASCADE, related_name='tour_participations', to=settings.AUTH_USER_MODEL),
        ),
    ]
