# Generated by Django 5.2.4 on 2025-08-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tourguideassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourparticipant',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=10),
        ),
    ]
