# Generated by Django 5.2.4 on 2025-08-17 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_tourparticipant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourparticipant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tourparticipant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='tourparticipant',
            constraint=models.UniqueConstraint(fields=('tour', 'user'), name='unique_tour_user'),
        ),
    ]
