# Generated by Django 5.2.4 on 2025-11-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_tourparticipant_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourparticipant',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
