# Generated by Django 5.2.4 on 2025-08-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], default='image', max_length=20),
        ),
    ]
